### ISSUE TITLE
[FEAT] Magento CRON logs to stdout

### ISSUE THREAD

**Issue by gitrequests** [graycoreio/magento2-stdlogging#25]
# :bulb: Feature request

## Magento CRON logs to stdout

As written in the documentation [here](https://experienceleague.adobe.com/docs/commerce-operations/configuration-guide/cli/enable-logging.html?lang=en) from version Magento 2.3.1 CRON logs are sent to a separate file (`<install-directory>/var/log/cron.log`). In the Docker environment, they can also be sent to standard output.

I found that the cron log configuration is available in `<install-directory>/vendor/magento/module-cron/etc/di.xml`.
Here are two virtual types: `Magento\Cron\Model\VirtualLogger` and `Magento\Cron\Model\VirtualLoggerHandler`.

## Environment
```
magento2-stdlogging version: 2.0.0
Magento version: 2.4.6 
PHP Version version: 8.2.4 
```

**Comment by gitrequests** [comment]
I suggest adding DI configuration to magento2-stdlogging/etc/di.xml
```php
<preference for="Magento\Cron\Model\VirtualLoggerHandler" type="Graycore\StdLogging\Handler\Stdout"/>
```
I added the config to /app/etc/di.xml and it solved the problem

**Comment by damienwebdev** [comment]
@gitrequests please feel to open a PR and I'll merge this.

**Comment by gitrequests** [comment]
It seems to depend on the situation. I started to have duplicate logs from monolog and crond from docker (docker output stdout 2 times). It turns out that you need to suppress logs either from crond (from docker in my case) or from monolog.

If anyone is interested in how to suppress logs from monolog for magento-cron, here is the code:
```php
<preference for="Magento\Cron\Model\VirtualLoggerHandler" type="Monolog\Handler\NoopHandler"/>
```

The issue can be closed, let people make a decision based on the comment.
