### ISSUE TITLE
[FEAT] What's next? What do you need?

### ISSUE THREAD

**Issue by damienwebdev** [graycoreio/magento2-stdlogging#5]
# :bulb: Feature request

## Feature Name
Feature Wishlist

## The Desired Behavior
I wrote this package to make my life easier. How can it make your life easier?

**Comment by damienwebdev** [comment]
@marciomaciel @benjick as you guys use this, is there anything that this package could do better?

**Comment by benjick** [comment]
Hey. Thanks for updating it. I haven't tried it yet since I just tried to
install it but I'll let you know!

Cheers
Max
